# Generated by Django 3.2.4 on 2021-06-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210606_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='default title', upload_to='images/'),
            preserve_default=False,
        ),
    ]
