# Generated by Django 3.2.4 on 2021-06-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='photo',
        ),
    ]
